# Generated by Django 5.0.2 on 2025-06-03 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.CharField(max_length=20)),
                ('user', models.ManyToManyField(through='account.Features', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='features',
            name='roles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.roles'),
        ),
    ]
