# Generated by Django 5.0.2 on 2025-06-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_bvn'),
    ]

    operations = [
        migrations.CreateModel(
            name='BvnRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Bvn',
        ),
    ]
